services:
  http:
    container_name: "http_cqrls"
    build:
      context: "./"
      dockerfile: "./docker/http.Dockerfile"
    ports:
      - "8080:8080"
    environment:
      PORT_HTTP: ":8080"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty"
      POSTGRES_DB: "postgres"
      POSTGRES_SSL: "disable"
#      RMQ_PATH: "rabbitmq-broker:5672/"
#      RMQ_LOG: "guest"
#      RMQ_PASS: "guest"
#    depends_on:
#      - rabbitmq-broker
#      - postgres

  postgres:
    container_name: "postgres"
    image: postgres:latest
    restart: always
    user: "postgres"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty"
      POSTGRES_DATABASE: "postgres"
    #    volumes:
    #      - ./storage/postgres/database.sql:/docker-entrypoint-initdb.d/database.sql
    ports:
      - "5432:5432"