// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mock

import (
	models "CQRS-simple/pkg/models"

	mock "github.com/stretchr/testify/mock"
)

// QueueCreateInterface is an autogenerated mock type for the QueueCreateInterface type
type QueueCreateInterface struct {
	mock.Mock
}

// QueueCreateCache provides a mock function with given fields: up
func (_m *QueueCreateInterface) QueueCreateCache(up models.Cud) error {
	ret := _m.Called(up)

	var r0 error
	if rf, ok := ret.Get(0).(func(models.Cud) error); ok {
		r0 = rf(up)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// QueueCreateWrite provides a mock function with given fields: c
func (_m *QueueCreateInterface) QueueCreateWrite(c models.Cud) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(models.Cud) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
