// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	models "CQRS-simple/pkg/models"

	mock "github.com/stretchr/testify/mock"
)

// ReadServInterface is an autogenerated mock type for the ReadServInterface type
type ReadServInterface struct {
	mock.Mock
}

// GetAllUsers provides a mock function with given fields:
func (_m *ReadServInterface) GetAllUsers() (*[]models.User, error) {
	ret := _m.Called()

	var r0 *[]models.User
	if rf, ok := ret.Get(0).(func() *[]models.User); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]models.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserPosts provides a mock function with given fields: userID
func (_m *ReadServInterface) UserPosts(userID string) (models.UserPosts, error) {
	ret := _m.Called(userID)

	var r0 models.UserPosts
	if rf, ok := ret.Get(0).(func(string) models.UserPosts); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(models.UserPosts)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
